language: node_js

cache:
  npm: true

env:
  global:
    - REACT_ENV=development
    - REACT_APP_LOG_LEVEL=debug
    - REACT_APP_NETWORK_ID=4447
    - MNEMONIC="choice congress hobby buddy dutch busy army eager empty solution start grunt"
    - CI=false

script:
  - npm run coveralls
  - npm run build

after_failure:
  - cat /home/travis/.npm/_logs/*-debug.log
