# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ react-native ]
  pull_request:
    branches: [ react-native ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: Detox Tests
    runs-on: macos-latest      
    steps:
      - name: fix max_user_watches
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10.15.3
      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
      - name: Install npm dependencies
        run: |
          npm ci
      - name: Prepare env
        env: # Or as an environment variable
          SENTRYRC: ${{ secrets.sentryrc_file }}
        run: |
          echo "$SENTRYRC" > android/sentry.properties
          cp .env.dev .env
      - name: Use specific Java version for sdkmanager to work
        uses: joschi/setup-jdk@v1
        with:
          java-version: 'openjdk8'
          architecture: 'x64'
      - name: run detox build & test
        run: npm run test:android
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps: 
      - name: fix max_user_watches
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10.15.3
      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install npm dependencies
        run: |
          npm ci
      - name: Prepare env
        env: # Or as an environment variable
          SENTRYRC: ${{ secrets.sentryrc_file }}
        run: |
          echo "$SENTRYRC" > android/sentry.properties
          cp .env.dev .env
      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
