
name: iOS & Android Quick Release

on:
  push:
    branches: [master, staging, next]

  workflow_dispatch:

jobs:
  deploy:
    name: Hot Code Push
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'release') && github.event.head_commit.message =~ .*\d{4} }}
    steps:
      - name: Code push release
        env:
          BUILD_NUMBER: ${{ github.run_number }}
        run: |
          echo "Code push release target version "${BUILD_NUMBER}""
          npx appcenter codepush release-react --token "${{ env.APPCENTER_TOKEN }}" -a "${{ env.APPCENTER_NAME }}" -d Production  -t "${BUILD_NUMBER}"
