name: Deploy preparation

on:
  workflow_call:

jobs:
  pre_checks:
    name: Pre-checks
    runs-on: ubuntu-latest
    steps:
      - name: Pre-checks - Env is Dev
        run: |
          echo "ENV=development" >> $GITHUB_ENV
          echo "SECRET_NAME=DEV_ENV" >> $GITHUB_ENV
          echo "APPCENTER_NAME=GoodDollar/GoodDollar-Android-development" >> $GITHUB_ENV
          echo "APPCENTER_TOKEN=${{ secrets.APPCENTER_ANDROID_DEV }}" >> $GITHUB_ENV
          echo "APPCENTER_CODEPUSH_TOKEN=${{ secrets.APPCENTER_CODEPUSH_DEV }}" >> $GITHUB_ENV
      - name: Pre-checks - Env is QA
        if: ${{ endsWith(github.ref, '/staging') }}
        run: |
          echo "ENV=staging" >> $GITHUB_ENV
          echo "SECRET_NAME=STAGING_ENV" >> $GITHUB_ENV
          echo "APPCENTER_NAME=GoodDollar/GoodDollar-Android-staging" >> $GITHUB_ENV
          echo "APPCENTER_TOKEN=${{ secrets.APPCENTER_ANDROID_STAGING }}" >> $GITHUB_ENV
          echo "APPCENTER_CODEPUSH_TOKEN=${{ secrets.APPCENTER_CODEPUSH_STAGING }}" >> $GITHUB_ENV
      - name: Pre-checks - Env is PROD
        if: ${{ endsWith(github.ref, '/next') }}
        run: |
          echo "ENV=prod" >> $GITHUB_ENV
          echo "SECRET_NAME=PROD_ENV" >> $GITHUB_ENV
          echo "APPCENTER_NAME=GoodDollar/GoodDollar-Android-production" >> $GITHUB_ENV
          echo "APPCENTER_TOKEN=${{ secrets.APPCENTER_ANDROID_PROD }}" >> $GITHUB_ENV
          echo "APPCENTER_CODEPUSH_TOKEN=${{ secrets.APPCENTER_CODEPUSH_PROD }}" >> $GITHUB_ENV
  install_deps:
    name: Dependencies install
    runs-on: ubuntu-latest
    steps:
      - name: Cache & install npm dependencies
        uses: bahmutov/npm-install@v1
        with:
          install-command: yarn --frozen-lockfile
  add_secrets:
    name: Add secrets
    runs-on: ubuntu-latest
    steps:
      - name: add .env secrets
        env:
          SENTRYRC: ${{ secrets.sentryrc_file }}
        run: |
          env_name="${{ env.ENV }}"
          echo $env_name
          cat .env.$env_name
          echo "adding secrets to .env.$env_name file: ${{ env.SECRET_NAME }}"
          echo "$SENTRYRC" > android/sentry.properties
          echo "${{ secrets[env.SECRET_NAME] }}" >> .env.$env_name
          echo "REACT_APP_CODE_PUSH_KEY=${{ env.APPCENTER_CODEPUSH_TOKEN }}"  >> .env.$env_name
