# This is a basic workflow to help you get started with Actions

name: Web CI/CD v1

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

  on:
    workflow_dispatch:
      inputs:
        release:
          description: 'release type'
          required: true
          default: 'qa'
        version:
          description: 'version bump'
          required: false
          default: 'prerelease'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    name: Release
    if: "contains(github.event.head_commit.message,'release: prod')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 10.15.3
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: 'staging'
      - name: update version and push
        run: |
          git config --local user.email "techadmin@gooddollar.org"
          git config --local user.name "Techadmin"
          npm install -g auto-changelog
          npm version minor -m "chore: release ${{ github.event.inputs.name }} version %s [skip ci]"
          git push https://${{ secrets.GIT_AUTH }}@github.com/GoodDollar/GoodDAPP staging --follow-tags',
      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     branch: 'production'
      #     tags: true
      #     force: true
      #     github_token: ${{ secrets.GIT_AUTH }}
      - name: Merge staging -> master
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          target_branch: master
          github_token: ${{ secrets.GIT_AUTH }}

  test:
    name: Unit Tests
    if: "!contains(github.event.head_commit.message,'release:') && !contains(github.event.head_commit.message,'skip ci')"
    env:
      REACT_ENV: 'development'
      TEST_REACT_NATIVE: false
      BUNDLESIZE_GITHUB_TOKEN: 63f6d1717c6652d63234cf9629977b08f4bac3fd
      MNEMONIC: 'myth like bonus scare over problem client lizard pioneer submit female collect'
      ADMIN_MNEMONIC: 'they bus duty candy uncover assault bullet kitchen kit acid spin physical'
      CI: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10.15.3
      - name: Install npm dependencies
        uses: bahmutov/npm-install@v1

      - name: prepare blockchain for test
        run: npm run test:setup

      - name: run tests and code coverage
        run: |
          npm run coverage
          npm run coveralls || true
          pkill -f ganache
