# This is a basic workflow to help you get started with Actions

name: Web CI/CD v1

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    name: Release
    if: "contains(github.event.head_commit.message,'release: prod')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
          branch: 'staging'
      - name: update version and push
        run: |
          npm install -g auto-changelog
          npm version minor -m "chore: release prod version %s [skip ci]"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: 'production'
          tags: true
          force: true
      - name: Merge staging -> master
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          target_branch: master

  test:
    name: Unit Tests
    if: "!contains(github.event.head_commit.message,'release:') && !contains(github.event.head_commit.message,'skip ci')"
    env:
      REACT_ENV: 'development'
      TEST_REACT_NATIVE: false
      BUNDLESIZE_GITHUB_TOKEN: 63f6d1717c6652d63234cf9629977b08f4bac3fd
      MNEMONIC: 'myth like bonus scare over problem client lizard pioneer submit female collect'
      ADMIN_MNEMONIC: 'they bus duty candy uncover assault bullet kitchen kit acid spin physical'
      CI: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10.15.3
      - name: Install npm dependencies
        uses: bahmutov/npm-install@v1

      - name: prepare blockchain for test
        run: npm run test:setup

      - name: run tests and code coverage
        run: |
          npm run coverage
          npm run coveralls || true
          pkill -f ganache
